pipeline {
    agent { node { label 'maven' } }
    options { skipDefaultCheckout true }
        stages {
            stage('Checkout') {
                sendNotification('started', 'team@example.com')
                steps {
                    git branch: 'notifications',
                    url: 'https://github.com/sjmeyer470/DO400-apps'
                }
            }
            stage('Test') {
                steps {
                    dir('simple-calculator') {
                    sh './mvnw clean test'
                }
            }
        }
    }
}

void sendNotification(String action, String email) {
    mail to: "${email}",
    subject: "Pipeline ${action}: ${currentBuild.fullDisplayName}",
    body: "The following pipeline ${action}: ${env.BUILD_URL}"
}